name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
         inputs:
             debug:
                 description: "Select the option"
                 required: true
                 type: boolean
                 default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
        - name:  "[debug] Print start-up data"
          if: ${{ inputs.debug}}
          run: |
              echo "Triggered by: ${{ github.event_name}}"
              echo "This is branch name ${{github.event.ref}}"
              echo "This is branch name ${{github.sha}}"
              echo "This is branch name ${{runner.os}}"
        - name: "[debug] Print when triggered from main"
          if: ${{ inputs.debug && github.ref}} == 'refs/heads/main'
          run:  |
               echo "I was triggered from main"

        - name: "Greeting"
          run: |
              echo "Hello, world"

                
             

