name: This is workflow
on:
     workflow_dispatch:
         inputs:
            color:
                description: "Please select the color"
                type: choice
                required: false
                options:
                    - red
                    - blue
                    - green
            days:
                required: true
                type: choice
                description: "type days"
                options:
                    - mon
                    - tues


jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - name: print the color name
        run: |
                echo "Print the color ${{github.event.inputs.color}}"
                echo "Print the color ${{github.event_name }}"
                echo "Print the value ${{github.event.inputs.days}}"
                





