name: testing
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: This is just an example
              run:   echo '${{ toJson(github.repository) }}'
