name: testing
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - if:  ${{ github.repository }} == "xxxutsavdixit/test2ndweek"
           run: |
              echo : "this si tes hnm"
 